### PR TITLE
Added mage sdk namespace

### PR DESCRIPTION
**Pull request by dyoxyne**
I just put the new Mage SDK namespace.

### CODE REVIEW

**Comment by AlmirKadric** [comment]
I don't think the MAGE SDK namespace belongs in here.

A better way (if you don't mind doing it), would be for this code base to have its own version of the mono-singleton class. Similarly to the mage SDK it can be wrapped in a namespace to prevent overlapping classnames.

@nullorvoid @kefniark what do you guys think?

**Comment by nullorvoid** [comment]
I was looking at this with @dyoxyne for the moment I'm not sure what to do with it.  I would like to remove it completely and go with the one in WizUtils, or something else entirely depending on if its needed.  At the moment in the other project we are only using Task for one thing, which is background threading large json parsing jobs.

We had a look at removing it from @dyoxyne project but its a larger refactor than is sensible at the moment, in short, not sure.

Also the HTTP class in the Mage sdk needs some work to make it nice when dealing with single threaded systems, and Unity is already moving away from that with .Net 4.5 async and await which I guess is due some time next year.

**Comment by dyoxyne** [comment]
I am more willing to remove this as a submodule and put this directly in the GHM code instead of duplicating MonoSingleton for now.

The mid/long-term goal is to remove the usage of TaskManagerMainThread.

**Comment by AlmirKadric** [comment]
@dyoxyne sounds like a plan to me 👍 
feel free to close this PR and make the changes directly in GHM
P.S. this is a public thread so replace project names with codenames please

**Comment by dyoxyne** [comment]
@AlmirKadric Ok.

**Pull request closed without merging**
